apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: bb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb
  labels:
    app: bb
    service: bb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb
      service: bb
  template:
    metadata:
      labels:
        app: bb
        service: bb
    spec:
      serviceAccountName: bb
      
      containers:
      - name: bb-container
        image: hhana982/bb:1.<version>
        ports:
        - containerPort: 5000
        
        env: 