apiVersion: v1
kind: Service
metadata:
  name: bb
  labels:
    app: bb
    service: bb
spec:
  selector:
    app: bb
    service: bb
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP